config { 
    type: "operations",
    hasOutput: true
}

CREATE OR REPLACE FUNCTION ${self()} (responseMessages ARRAY<JSON>)
RETURNS STRING
LANGUAGE js
AS r"""

let agentResponse = "";
if (responseMessages && Array.isArray(responseMessages)) {
    responseMessages.forEach(message => {
    if (message.text && message.text.text) {
        agentResponse += message.text.text.join(" ");
    }
    });
}
return agentResponse;
""";
