config { 
    type: "operations" 
}

CREATE FUNCTION dfcx.agentResponse(responseMessages ARRAY<JSON>)
RETURNS STRING
LANGUAGE js
AS r"""

let agentResponse = "";
if (responseMessages && Array.isArray(responseMessages)) {
    responseMessages.forEach(message => {
    if (message.text && message.text.text) {
        agentResponse += message.text.text.join(" ");
    }
    });
}
return agentResponse;
""";
